version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Find
          command: find .
      - run:
          name: Restore
          command: dotnet restore ./MyConsoleApp/MyConsoleApp/MyConsoleApp1.csproj
      - run:
          name: Build
          command: dotnet build ./MyConsoleApp/MyConsoleApp/MyConsoleApp.csproj
      - run:
          name: Test
          command: dotnet test ./MyConsoleApp/MyConsoleApp.Test/MyConsoleApp.Test.csproj
      - store_artifacts:
          path: coverage
