version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: find .
      - run: dotnet restore ./MyConsoleApp/MyConsoleApp/MyConsoleApp.csproj
      - run: dotnet build ./MyConsoleApp/MyConsoleApp/MyConsoleApp.csproj
      - run: dotnet test --no-build ./MyConsoleApp/MyConsoleApp.Test/MyConsoleApp.Test.csproj
