workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore ./MyConsoleApp/MyConsoleApp/MyConsoleApp.csproj
      - run:
          name: Build
          command: dotnet build ./MyConsoleApp/MyConsoleApp/MyConsoleApp.csproj
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Test
          command: dotnet test ./MyConsoleApp/MyConsoleApp.Test/MyConsoleApp.Test.csproj
