name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.103
    - name: Install dependencies
      run: dotnet restore ./MyConsoleApp/MyConsoleApp/MyConsoleApp.csproj
    - name: Build
      run: dotnet build ./MyConsoleApp/MyConsoleApp/MyConsoleApp.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./MyConsoleApp/MyConsoleApp.Test/MyConsoleApp.Test.csproj --no-restore --verbosity normal
