# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}
    - name: Setup Version ID
      run: |
        VERSION=`git describe --abbrev=0` ; echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: MyConsoleApp
    - name: Build
      run: dotnet build -property:Version=$VERSION --configuration Release --no-restore
      working-directory: MyConsoleApp
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: MyConsoleApp
    - name: Publish
      run: dotnet publish --no-build --configuration Release -o publish MyConsoleApp
      working-directory: MyConsoleApp
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MyConsoleApp-${{ env.VERSION }}
        path: MyConsoleApp/publish
