# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches: [ master ]
    types: [closed, labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel test
jobs:
  check:
    if: > 
      ${{github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'safe to release') }}
    name: Check PR merged Status and Label
    runs-on: ubuntu-latest
    outputs:
      pr_merged: ${{ steps.pr_status.outputs.PR_MERGED }}
      pr_label_has_safe_to_release: ${{ steps.pr_status.outputs.PR_LABEL_HAS_SAFE_TO_RELEASE }}
      current_branch: ${{ steps.pr_status.outputs.CURRENT_BRANCH }}
      event_number: ${{ steps.pr_status.outputs.EVENT_NUMBER }}
    steps:
      - uses: actions/checkout@v2
      - name: Set PR Status
        id: pr_status
        run: |
          echo ::set-output name=PR_MERGED::${{github.event.pull_request.merged}}
          echo ::set-output name=PR_LABEL_HAS_SAFE_TO_RELEASE::${{ contains(github.event.pull_request.labels.*.name, 'safe to release') }}
          echo ::set-output name=CURRENT_BRANCH::${GITHUB_REF#refs/*/}
          echo ::set-output name=EVENT_NUMBER::${{ github.event.number }}
      - name: Check PR Status
        run: |
          echo ${{ steps.pr_status.outputs.PR_MERGED }}
          echo ${{ steps.pr_status.outputs.PR_LABEL_HAS_SAFE_TO_RELEASE }}
          echo ${{ steps.pr_status.outputs.CURRENT_BRANCH }}
          echo ${{ steps.pr_status.outputs.EVENT_NUMBER }}
  once:
    name: Create single release for all build_release
    needs: check
    env:
      working-directory: MyConsoleApp
      pr_merged: ${{ needs.check.outputs.pr_merged }}
      pr_label_has_safe_to_release: ${{ needs.check.outputs.pr_label_has_safe_to_release }}
      current_branch: ${{ needs.check.outputs.current_branch }}
      event_number: ${{ needs.check.outputs.event_number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Run a multi-line script
        run: |
          export tag_major=major
          export tag_minor=minor
          export tag_patch=patch
          export default_semvar_bump=${tag_patch}
          export with_v=false
          export release_branches=master

          echo '*** Configuration ****'

          echo "Working-driectory: ${{env.working-directory}}"
          echo "PR Merged: ${{env.pr_merged}}"
          echo "PR Label has safe to release: ${{env.pr_label_has_safe_to_release}}"
          echo "Current Branch: ${{env.current_branch}}"
          echo "Event Number: ${{env.event_number}}"
          echo "DEFAULT_BUMP: ${default_semvar_bump}"
          echo "WITH_V: ${with_v}"
          echo "RELEASE_BRANCHES: ${release_branches}"
