# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches: [ master ]
    types: [closed, labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  once:
    if: >
      ${{github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'safe to release') }}
    name: Create single release for all build_release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Run a multi-line script
        run: |
          export tag_major=major
          export tag_minor=minor
          export tag_patch=patch
          export default_semvar_bump=${tag_patch}
          export with_v=false
          export release_branches=master

          echo '*** Configuration ****'
          echo "DEFAULT_BUMP: ${default_semvar_bump}"
          echo "WITH_V: ${with_v}"
          echo "RELEASE_BRANCHES: ${release_branches}"
          echo "Test Current Branch: $(echo ${GITHUB_REF#refs/*/})"

          export current_branch=$(git rev-parse -abbrev-ref HEAD)

          echo "Current Branch: ${current_branch}"
          echo ${{ github.event.number }},
          echo ${{ github.event.workflow_run.event }},
          echo ${{ github.event.pull_request.labels.*.name }},
          echo ${{ github.event.pull_request.merged }}
